  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/rust:latest
      steps:
        - checkout
        - run:
            name: versions
            command: rustc --version; cargo --version; rustup --version
        - run:
            name: check
            command: cargo check --verbose   
        - run:
            name: build
            command: cargo build --release